### DISCUSSION TITLE
支持合并多个配置

### DISCUSSION THREAD

**Discussion by potoo0** [MetaCubeX/ClashMetaForAndroid#225] [Ideas]
就像 clash verge 一样，可以建多个 merge 类型的配置，这些配置会依次把上一步（初始从订阅获取）的配置做覆盖/追加操作

例如 merge 类型的配置可以写以下标签来追加配置

```yml
# Merge Template for clash verge
# The `Merge` format used to enhance profile

prepend-rules:

prepend-rule-providers:

prepend-proxies:

prepend-proxy-providers:

prepend-proxy-groups:

append-rules:

append-rule-providers:

append-proxies:

append-proxy-providers:

append-proxy-groups:


```
