### DISCUSSION TITLE
求助，为何同一份配置，同样的网络环境，连接同一个网站，在Clash Verge Rev能正常连接，在CMFA中连不上？

### DISCUSSION THREAD

**Discussion by wha4up** [MetaCubeX/ClashMetaForAndroid#232] [Q&A]
配置如下：
```
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
clash-for-android:
    append-system-dns: false
dns:
  enable: true
  listen: 127.0.0.1:53
  default-nameserver: [223.5.5.5, 119.29.29.29]
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter: ["*", "*.lan", "*.localdomain", "*.example", "*.invalid", "*.localhost", "*.test", "*.local", "*.home.arpa", time.*.com, time.*.gov, time.*.edu.cn, time.*.apple.com, time-ios.apple.com, time1.*.com, time2.*.com, time3.*.com, time4.*.com, time5.*.com, time6.*.com, time7.*.com, ntp.*.com, ntp1.*.com, ntp2.*.com, ntp3.*.com, ntp4.*.com, ntp5.*.com, ntp6.*.com, ntp7.*.com, "*.time.edu.cn", "*.ntp.org.cn", +.pool.ntp.org, time1.cloud.tencent.com, music.163.com, "*.music.163.com", "*.126.net", musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, "*.kuwo.cn", api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, "*.y.qq.com", streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, "*.xiami.com", "*.music.migu.cn", music.migu.cn, +.msftconnecttest.com, +.msftncsi.com, localhost.ptlogin2.qq.com, localhost.sec.qq.com, +.qq.com, +.tencent.com, +.steamcontent.com, +.srv.nintendo.net, "*.n.n.srv.nintendo.net", +.cdn.nintendo.net, +.stun.playstation.net, xbox.*.*.microsoft.com, "*.*.xboxlive.com", xbox.*.microsoft.com, xnotify.xboxlive.com, +.battlenet.com.cn, +.wotgame.cn, +.wggames.cn, +.wowsgame.cn, +.wargaming.net, proxy.golang.org, stun.*.*, stun.*.*.*, +.stun.*.*, +.stun.*.*.*, +.stun.*.*.*.*, +.stun.*.*.*.*.*, heartbeat.belkin.com, "*.linksys.com", "*.linksyssmartwifi.com", "*.router.asus.com", mesu.apple.com, swscan.apple.com, swquery.apple.com, swdownload.apple.com, swcdn.apple.com, swdist.apple.com, lens.l.google.com, stun.l.google.com, na.b.g-tun.com, +.nflxvideo.net, "*.square-enix.com", "*.finalfantasyxiv.com", "*.ffxiv.com", "*.ff14.sdo.com", ff.dorado.sdo.com, "*.mcdn.bilivideo.cn", +.media.dssott.com, shark007.net, Mijia Cloud, +.cmbchina.com, +.cmbimg.com, adguardteam.github.io, adrules.top, anti-ad.net, local.adguard.org, static.adtidy.org, +.sandai.net, +.n0808.com, +.3gppnetwork.org, +.uu.163.com, ps.res.netease.com]
  nameserver: [tls://223.5.5.5:853, https://223.6.6.6/dns-query, https://120.53.53.53/dns-query]
  nameserver-policy: {+.tmall.com: 223.5.5.5, +.taobao.com: 223.5.5.5, +.alicdn.com: 223.5.5.5, +.aliyun.com: 223.5.5.5, +.alipay.com: 223.5.5.5, +.alibaba.com: 223.5.5.5, +.qq.com: 119.29.29.29, +.tencent.com: 119.29.29.29, +.weixin.com: 119.29.29.29, +.qpic.cn: 119.29.29.29, +.jd.com: 119.29.29.29, +.bilibili.com: 119.29.29.29, +.hdslb.com: 119.29.29.29, +.163.com: 119.29.29.29, +.126.com: 119.29.29.29, +.126.net: 119.29.29.29, +.127.net: 119.29.29.29, +.netease.com: 119.29.29.29, +.baidu.com: 223.5.5.5, +.bdstatic.com: 223.5.5.5, +.bilivideo.+: 119.29.29.29, +.iqiyi.com: 119.29.29.29, +.douyinvod.com: 180.184.1.1, +.douyin.com: 180.184.1.1, +.douyincdn.com: 180.184.1.1, +.douyinpic.com: 180.184.1.1, +.feishu.cn: 180.184.1.1}
  fallback: [tls://101.101.101.101:853,https://101.101.101.101/dns-query, https://public.dns.iij.jp/dns-query, https://208.67.220.220/dns-query]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 127.0.0.1/32], domain: [+.google.com, +.facebook.com, +.twitter.com, +.youtube.com, +.xn--ngstr-lra8j.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com, +.paoluz.com, +.paoluz.link, +.paoluz.xyz, +.sodacity-funk.xyz, +.nloli.xyz,+.jsdelivr.net, +.proton.me]}
proxies:
  - {name: "☁️ Warp-A",type: wireguard,server: 162.159.195.37,port: 3581,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-B",type: wireguard,server: 162.159.195.13,port: 1387,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-C",type: wireguard,server: 162.159.195.51,port: 7559,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-D",type: wireguard,server: 162.159.195.230,port: 939,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-E",type: wireguard,server: 162.159.195.18,port: 8886,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-F",type: wireguard,server: 162.159.195.195,port: 8886,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-G",type: wireguard,server: 162.159.195.223,port: 1387,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-H",type: wireguard,server: 162.159.195.26,port: 8886,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-I",type: wireguard,server: 162.159.195.26,port: 8886,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
  - {name: "☁️ Warp-J",type: wireguard,server: 162.159.195.107,port: 942,ip: 172.16.0.2,private-key: *,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,remote-dns-resolve: false,udp: true}
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列, ♻️ 自动选择, ☁️ Warp-A, ☁️ Warp-B, ☁️ Warp-C, ☁️ Warp-D, ☁️ Warp-E, ☁️ Warp-F, ☁️ Warp-G, ☁️ Warp-H, ☁️ Warp-I, ☁️ Warp-J, DIRECT]}
  - {name: ♻️ 自动选择, type: url-test, url: http://www.gstatic.com/generate_204, interval: 3600, tolerance: 200, proxies: [⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列, ☁️ Warp-A, ☁️ Warp-B, ☁️ Warp-C, ☁️ Warp-D, ☁️ Warp-E, ☁️ Warp-F, ☁️ Warp-G, ☁️ Warp-H, ☁️ Warp-I, ☁️ Warp-J]}
  - {name: ⚖️ 负载均衡-轮询, type: load-balance, url: http://www.google.com/generate_204, interval: 300, strategy: round-robin, proxies: [☁️ Warp-A, ☁️ Warp-B, ☁️ Warp-C, ☁️ Warp-D, ☁️ Warp-E, ☁️ Warp-F, ☁️ Warp-G, ☁️ Warp-H, ☁️ Warp-I, ☁️ Warp-J]}
  - {name: ⚖️ 负载均衡-散列, type: load-balance, url: http://www.google.com/generate_204, interval: 300, strategy: consistent-hashing, proxies: [☁️ Warp-A, ☁️ Warp-B, ☁️ Warp-C, ☁️ Warp-D, ☁️ Warp-E, ☁️ Warp-F, ☁️ Warp-G, ☁️ Warp-H, ☁️ Warp-I, ☁️ Warp-J]}
  - {name: 🌍 国外媒体, type: select, proxies: [🚀 节点选择, 🎯 全球直连, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列
  - {name: 📲 电报信息, type: select, proxies: [🚀 节点选择, 🎯 全球直连, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: Ⓜ️ 微软服务, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}
  - {name: 🍎 苹果服务, type: select, proxies: [🚀 节点选择, 🎯 全球直连]}
  - {name: 📢 谷歌FCM, type: select, proxies: [🚀 节点选择, 🎯 全球直连]}
  - {name: 🎯 全球直连, type: select, proxies: [DIRECT]}
  - {name: 🛑 广告拦截, type: select, proxies: [REJECT]}
  - {name: 📈 网络测试, type: select, proxies: [🎯 全球直连, ☁️ Warp-A, ☁️ Warp-B, ☁️ Warp-C, ☁️ Warp-D, ☁️ Warp-E, ☁️ Warp-F, ☁️ Warp-G, ☁️ Warp-H, ☁️ Warp-I, ☁️ Warp-J]}
  - {name: 🤖 人工智能, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 🎮 游戏服务, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}
  - {name: 🎥 奈飞视频, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 📽️ 迪士尼+, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 🎞️ Max, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 🎬 Prime Video, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 🍎 Apple TV+, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 📹 油管视频, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 🎵 TikTok, type: select, proxies: [🚀 节点选择, ⚖️ 负载均衡-轮询, ⚖️ 负载均衡-散列]}
  - {name: 📺 哔哩哔哩, type: select, proxies: [🎯 全球直连, 🚀 节点选择, ☁️ Warp-A, ☁️ Warp-B, ☁️ Warp-C, ☁️ Warp-D, ☁️ Warp-E, ☁️ Warp-F, ☁️ Warp-G, ☁️ Warp-H, ☁️ Warp-I, ☁️ Warp-J]}
  - {name: 🇨🇳 直连域名, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}
  - {name: 🇨🇳 直连 IP, type: select, proxies: [🎯 全球直连, 🚀 节点选择]}
  - {name: 🪜 代理域名, type: select, proxies: [🚀 节点选择, 🎯 全球直连]}
  - {name: 🖥️ 直连软件, type: select, proxies: [🎯 全球直连]}
  - {name: 🔒 私有网络, type: select, proxies: [🎯 全球直连]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🚀 节点选择, 🎯 全球直连]}

rule-providers:
  ads:
    type: http
    behavior: domain
    format: text
    path: ./rules/ads.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ads.list"
    interval: 86400

  applications:
    type: http
    behavior: classical
    format: text
    path: ./rules/applications.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/applications.list"
    interval: 86400

  private:
    type: http
    behavior: domain
    format: text
    path: ./rules/private.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/private.list"
    interval: 86400

  microsoft-cn:
    type: http
    behavior: domain
    format: text
    path: ./rules/microsoft-cn.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/microsoft-cn.list"
    interval: 86400

  apple-cn:
    type: http
    behavior: domain
    format: text
    path: ./rules/apple-cn.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/apple-cn.list"
    interval: 86400

  google-cn:
    type: http
    behavior: domain
    format: text
    path: ./rules/google-cn.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/google-cn.list"
    interval: 86400

  games-cn:
    type: http
    behavior: domain
    format: text
    path: ./rules/games-cn.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/games-cn.list"
    interval: 86400

  netflix:
    type: http
    behavior: domain
    format: text
    path: ./rules/netflix.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/netflix.list"
    interval: 86400

  disney:
    type: http
    behavior: domain
    format: text
    path: ./rules/disney.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/disney.list"
    interval: 86400

  max:
    type: http
    behavior: domain
    format: text
    path: ./rules/max.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/max.list"
    interval: 86400

  primevideo:
    type: http
    behavior: domain
    format: text
    path: ./rules/primevideo.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/primevideo.list"
    interval: 86400

  appletv:
    type: http
    behavior: domain
    format: text
    path: ./rules/appletv.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/appletv.list"
    interval: 86400

  youtube:
    type: http
    behavior: domain
    format: text
    path: ./rules/youtube.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/youtube.list"
    interval: 86400

  tiktok:
    type: http
    behavior: domain
    format: text
    path: ./rules/tiktok.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/tiktok.list"
    interval: 86400

  bilibili:
    type: http
    behavior: domain
    format: text
    path: ./rules/bilibili.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/bilibili.list"
    interval: 86400

  ai:
    type: http
    behavior: domain
    format: text
    path: ./rules/ai.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.list"
    interval: 86400

  networktest:
    type: http
    behavior: classical
    format: text
    path: ./rules/networktest.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/networktest.list"
    interval: 86400

  proxy:
    type: http
    behavior: domain
    format: text
    path: ./rules/proxy.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/proxy.list"
    interval: 86400

  cn:
    type: http
    behavior: domain
    format: text
    path: ./rules/cn.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/cn.list"
    interval: 86400

  netflixip:
    type: http
    behavior: ipcidr
    format: text
    path: ./rules/netflixip.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/netflixip.list"
    interval: 86400

  telegramip:
    type: http
    behavior: ipcidr
    format: text
    path: ./rules/telegramip.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/telegramip.list"
    interval: 86400

  privateip:
    type: http
    behavior: ipcidr
    format: text
    path: ./rules/privateip.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/privateip.list"
    interval: 86400

  cnip:
    type: http
    behavior: ipcidr
    format: text
    path: ./rules/cnip.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/cnip.list"
    interval: 86400

rules:
  - RULE-SET,ads,🛑 广告拦截
  - RULE-SET,applications,🖥️ 直连软件
  - RULE-SET,private,🔒 私有网络
  - RULE-SET,microsoft-cn,Ⓜ️ 微软服务
  - RULE-SET,apple-cn,🍎 苹果服务
  - RULE-SET,google-cn,📢 谷歌FCM
  - RULE-SET,games-cn,🎮 游戏服务
  - RULE-SET,netflix,🎥 奈飞视频
  - RULE-SET,disney,📽️ 迪士尼+
  - RULE-SET,max,🎞️ Max
  - RULE-SET,primevideo,🎬 Prime Video
  - RULE-SET,appletv,🍎 Apple TV+
  - RULE-SET,youtube,📹 油管视频
  - RULE-SET,tiktok,🎵 TikTok
  - RULE-SET,bilibili,📺 哔哩哔哩
  - RULE-SET,ai,🤖 人工智能
  - RULE-SET,networktest,📈 网络测试
  - RULE-SET,proxy,🪜 代理域名
  - RULE-SET,cn,🇨🇳 直连域名
  - RULE-SET,netflixip,🎥 奈飞视频,no-resolve
  - RULE-SET,telegramip,📲 电报信息,no-resolve
  - RULE-SET,privateip,🔒 私有网络,no-resolve
  - RULE-SET,cnip,🇨🇳 直连 IP
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
 ```

运行日志如下：
```
# Capture on 2024-05-18 20:58:18.925
20:58:18.928    Info: [APP] Logcat level: info
20:58:33.739 Warning: [TCP] dial 🤖 人工智能 (match RuleSet/ai) 172.19.0.1:42832(mark.via.gp) --> in.appcenter.ms:443 error: connect failed: dial tcp 4.152.45.235:443: i/o timeout
20:58:33.865 Warning: [TCP] dial 🪜 代理域名 (match RuleSet/proxy) 172.19.0.1:41884(mark.via.gp) --> www.google.com:443 error: connect failed: dial tcp [2404:6800:4012:4::2004]:443: i/o timeout
20:58:33.865 Warning: connect failed: dial tcp 172.217.163.36:443: i/o timeout
20:58:38.886 Warning: [TCP] dial 🪜 代理域名 (match RuleSet/proxy) 172.19.0.1:41902(mark.via.gp) --> www.google.com:443 error: connect failed: dial tcp [2404:6800:4012:4::2004]:443: i/o timeout
20:58:38.886 Warning: connect failed: dial tcp 172.217.163.36:443: i/o timeout
20:58:45.152 Warning: [TCP] dial 🤖 人工智能 (match RuleSet/ai) 172.19.0.1:42874(mark.via.gp) --> in.appcenter.ms:443 error: connect failed: dial tcp 4.152.45.235:443: i/o timeout
20:58:46.594 Warning: [TCP] dial 🪜 代理域名 (match RuleSet/proxy) 172.19.0.1:37594(mark.via.gp) --> clients1.google.com:443 error: connect failed: dial tcp 142.251.43.14:443: i/o timeout
20:58:46.594 Warning: connect failed: dial tcp [2404:6800:4012:3::200e]:443: i/o timeout
20:58:48.337    Info: [TCP] 172.19.0.1:38702(mark.via.gp) --> github.com:443 match RuleSet(proxy) using 🪜 代理域名[☁️ Warp-A]
20:58:50.082    Info: [TCP] 172.19.0.1:40106(mark.via.gp) --> avatars.githubusercontent.com:443 match RuleSet(proxy) using 🪜 代理域名[☁️ Warp-A]
20:58:51.394    Info: [TCP] 172.19.0.1:40722(mark.via.gp) --> github.githubassets.com:443 match RuleSet(proxy) using 🪜 代理域名[☁️ Warp-A]
20:58:51.631 Warning: [TCP] dial 🪜 代理域名 (match RuleSet/proxy) 172.19.0.1:37610(mark.via.gp) --> clients1.google.com:443 error: connect failed: dial tcp [2404:6800:4012:3::200e]:443: i/o timeout
20:58:51.631 Warning: connect failed: dial tcp 142.251.43.14:443: i/o timeout
20:58:51.957    Info: [TCP] 172.19.0.1:42566(mark.via.gp) --> alive.github.com:443 match RuleSet(proxy) using 🪜 代理域名[☁️ Warp-A]
```
