### DISCUSSION TITLE
怎么添加规则？

### DISCUSSION THREAD

**Discussion by jihaohaaaa** [MetaCubeX/ClashMetaForAndroid#378] [Q&A]
clash meta for android 怎么像在电脑端那样添加自定义的rule？
就像添加下面这样：
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,🔰节点选择
  - RULE-SET,proxy,🔰节点选择
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,🔰节点选择
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🔰节点选择

**Comment by Oimsae** [comment]
我也在寻找办法

**Comment by dreamoeu** [comment]
自己写，纯手搓

**Comment by SyberRabbit** [comment]
找到方法了吗？verge搓出来一堆配置，然后手机上找不到地方导入

**Reply by kands-code** [reply]
插眼，我也在找设置规则的方法

**Reply by SyberRabbit** [reply]
加号--文件--浏览文件--配置文件的三个点--导入--此时找不到yaml的话，点击左上角三个点，从根目录进`我小米手机是从"Redmi K60 Ultra"这个文件里进入`，然后再选路径，就能看到yaml了

**Reply by SyberRabbit** [reply]
更好的方式是：直接放到github的gist中，获取其raw链接，还是用订阅链接的方式导入，我现在就这样用呢

**Reply by SyberRabbit** [reply]
> 插眼，我也在找设置规则的方法

好像没回复到你，你来看看吧

**Reply by kands-code** [reply]
> > 插眼，我也在找设置规则的方法
> 
> 好像没回复到你，你来看看吧

回复到了，感谢🙏

**Reply by crazyi** [reply]
> 更好的方式是：直接放到github的gist中，获取其raw链接，还是用订阅链接的方式导入，我现在就这样用呢

能更详细一些介绍下怎么操作码？现在是有订阅链接，不知道怎么把上面的rule分流规则附加到现有的订阅规则之后

**Reply by SyberRabbit** [reply]
> > 更好的方式是：直接放到github的gist中，获取其raw链接，还是用订阅链接的方式导入，我现在就这样用呢
> 
> 能更详细一些介绍下怎么操作码？现在是有订阅链接，不知道怎么把上面的rule分流规则附加到现有的订阅规则之后

你直接看这个吧，我写成了完整的ymal配置，然后放到gist上，拿到raw链接，跟机场订阅的导入方式一样，导入到clash，就正常使用了。
https://raw.githubusercontent.com/SyberRabbit/About-Clash/refs/heads/clash-all-client-yaml/config.yaml

**Reply by 5kind** [reply]
自己写个本地的配置文件就行，选择“文件”方式，如果想要多个客户端同配置可以部署一个局域网的nginx之类的

**Reply by elna820** [reply]
> 自己写个本地的配置文件就行，选择“文件”方式，如果想要多个客户端同配置可以部署一个局域网的nginx之类的

大佬，小白请教下，我把Clash Verge里面的配置文件导出来，导入到手机端Clash Meta里面也能使用。但是有个问题，里面写死了机场的配置，如何让机场配置动态自动更新？谢谢

**Reply by SyberRabbit** [reply]
> > 自己写个本地的配置文件就行，选择“文件”方式，如果想要多个客户端同配置可以部署一个局域网的nginx之类的
> 
> 大佬，小白请教下，我把Clash Verge里面的配置文件导出来，导入到手机端Clash Meta里面也能使用。但是有个问题，里面写死了机场的配置，如何让机场配置动态自动更新？谢谢

proxy-providers配置中的interval，就是自动更新机场节点频率，
不知道你说的机场配置具体指哪些，我觉得只有机场节点需要更新，其他的配置都是自己写死就够了吧

**Reply by elna820** [reply]
> > > 自己写个本地的配置文件就行，选择“文件”方式，如果想要多个客户端同配置可以部署一个局域网的nginx之类的
> > 
> > 
> > 大佬，小白请教下，我把Clash Verge里面的配置文件导出来，导入到手机端Clash Meta里面也能使用。但是有个问题，里面写死了机场的配置，如何让机场配置动态自动更新？谢谢
> 
> proxy-providers配置中的interval，就是自动更新机场节点频率， 不知道你说的机场配置具体指哪些，我觉得只有机场节点需要更新，其他的配置都是自己写死就够了吧

谢谢各位老哥，我已经找到解决办法了。参考这个老哥写的：
Flclash覆写脚本分享-关于订阅源节点不固定场景的优化 https://linux.do/t/topic/1010793

层主提的问题也能一并解决，写JS脚本即可。

**Comment by boyliuxiaopeng** [comment]
看了，这个配置至少得修改：
1.nameserver
2.proxy-server-nameserver
3.proxy-providers.url
4.proxies
5.节点命名规则
6.局域网监听设置

**Comment by dreamoeu** [comment]
类似这个:
```yaml
allow-lan: true
bind-address: '*'
dns:
    default-nameserver:
        - 223.5.5.5
        - 119.29.29.29
    enable: true
    ipv6: false
    nameserver:
        - 223.5.5.5
        - 223.6.6.6
    proxy-server-nameserver:
        - https://doh.pub/dns-query
        - 119.29.29.29
        - https://dns.alidns.com/dns-query
        - tls://223.5.5.5:853
        - 223.5.5.5
external-controller: 127.0.0.1:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
proxy-groups:
  - name: 🔰节点选择
    type: select
    use:
      - "机场1"
proxy-providers:
  机场1:
    type: http
    url: "机场订阅URL"
    header:
      User-Agent: "ClashForAndroid/2.5.12.premium"
    path: ./Proxy_Providers/机场1.yaml
    interval: 86400
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,🔰节点选择
  - RULE-SET,proxy,🔰节点选择
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,🔰节点选择
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🔰节点选择
```
