### ISSUE TITLE
[BUG] 始终忽略外部配置文件的 `geox-url` 设置和外部添加的相关文件

### ISSUE THREAD

**Issue by nukemiko** [MetaCubeX/ClashMetaForAndroid#101]
### 描述此错误

客户端始终使用内置的 `geox-url` 下载 geosite.dat、geoip.dat、country.mmdb，对配置文件中的 `geox-url` 设置视而不见，即便直接在“浏览文件->外部资源文件列表”中添加以上文件也没有作用。

由于最近出现的严重网络干扰，客户端内置的 `geox-url` 设置（使用 testingcf.jsdelivr.net）在一些地区始终无法直接正常访问，因此导致规则涉及以上文件的配置文件无法通过校验，错误信息见屏幕截图。

相关 issue：#78

### 如何复现该错误

步骤 1：在配置文件中自定义 `geox-url`，例如：
```yaml
geox-url:
    geoip: https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    geosite: https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
    mmdb: https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/country.mmdb
```
配置文件需要使用至少一条 GeoSite 规则。

步骤 2：在 Clash Meta for Android 中导入该配置文件并，校验完毕后即可看到上述错误信息。

### 设备信息

- 机型: Redmi K30 Pro
- 系统类型: AOSP
- Android 版本: 13

### 应用信息

- 版本: 2.8.6
- 安装包文件名: cmfa-2.8.6-meta-arm64-v8a-release.apk
- 应用来源: https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/v2.8.6

### 配置文件

```yml
# 全局设置
mixed-port: 7531
redir-port: 7532
tproxy-port: 7533

allow-lan: true

mode: rule

log-level: info

ipv6: false

enable-process: true
find-process-mode: always

profile:
    store-selected: true
    store-fake-ip: true

global-client-fingerprint: firefox

geox-url:
    geoip: https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
    geosite: https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
    mmdb: https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/country.mmdb

experimental:

# TUN
tun:
    enable: true
    stack: system
    auto-route: true
    # auto-detect-interface: true
    dns-hijack:
        - any:53
        - tcp://any:53

# DNS
dns:
    enable: true
    prefer-h3: true
    listen: 0.0.0.0:65353
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
        - "*.lan"
        - "wifi.ccrgt.com"
        - "localhost.sec.qq.com"
        - "localhost.ptlogin2.qq.com"
        - "*.linksys.com"
        - "*.pool.ntp.org"
        # Router
        - "hiwifi.com"
        - "leike.cc"
        - "miwifi.com"
        - "my.router"
        - "peiluyou.com"
        - "phicomm.me"
        - "router.ctc"
        - "routerlogin.com"
        - "tendawifi.com"
        - "tplinkwifi.net"
        - "*.tplogin.cn"
        - "melogin.cn"
        - "*.melogin.cn"
        - “*.msftconnecttest.com”
        - “*.msftncsi.com”
        - "zte.home"
        - "*.stun.*.*"
        - "*.stun.*.*.*"
        - "*.stun.*.*.*.*"
        - "*.stun.*.*.*.*.*"
        - "lens.l.google.com"
        - "*.srv.nintendo.net"
        - "*.stun.playstation.net"
        - "xbox.*.*.microsoft.com"
        - "*.xboxlive.com"
        - "*.mcdn.bilivideo.cn"
    use-hosts: true
    default-nameserver:
        - 1.0.0.1
        - 1.1.1.1
        - 101.101.101.101
        - 115.231.220.34:777
        - 223.5.5.5
        - 119.29.29.29
    nameserver:
        - https://223.5.5.5/dns-query
        - https://120.53.53.53/dns-query
        - https://101.101.101.101/dns-query
        - https://185.222.222.222/dns-query
        - https://45.11.45.11/dns-query
        - https://1.1.1.1/dns-query
        - https://1.0.0.1/dns-query
    proxy-server-nameserver:
        - https://101.101.101.101/dns-query
        - https://185.222.222.222/dns-query
        - https://45.11.45.11/dns-query
        - https://1.1.1.1/dns-query
        - https://1.0.0.1/dns-query
        - https://223.5.5.5/dns-query
        - https://120.53.53.53/dns-query
    fallback:
        - https://101.101.101.101/dns-query
        - https://185.222.222.222/dns-query
        - https://45.11.45.11/dns-query
        - https://1.1.1.1/dns-query
        - https://1.0.0.1/dns-query
    fallback-filter:
        geoip: true
        geoip-code: CN
        geosite:
            - firefox
            - gfw
            - greatfire
            - github
            - gitlab
            - steam
            - gog
            - google
            - telegram
            - stackexchange
        domain:
            - "*.google.com"
            - "*.facebook.com"
            - "*.youtube.com"
            - "*.twitter.com"
            - "*.eu.org"
            - "*.v2ex.com"

hosts:
    "deepink.cn": "127.0.0.1"
    "*.deepink.cn": "127.0.0.1"

# 域名嗅探
sniffer:
    enable: true
    override-destination: false
    sniff:
        TLS:
            ports:
                - 443
                - 8443
        HTTP:
            ports:
                - 80
                - "8080-8880"
            override-destination: true
    force-domain:
        - "+.v2ex.com"
    skip-domain:
        - "Mijia Cloud"
        - "dlg.io.mi.com"
        - "*.apple.com"
        - "*.ccrgt.com"
        - "*.tplogin.cn"
        - "*.melogin.cn"
        - "melogin.cn"

# 代理集
proxy-providers:
    ...

# 规则配置
rules:
    - GEOSITE,category-ads-all,REJECT
    - GEOSITE,openai,PROXY
    - GEOSITE,steam@cn,DIRECT
    - GEOSITE,steam,PROXY
    - GEOSITE,gog@cn,DIRECT
    - GEOSITE,gog,PROXY
    - GEOSITE,hoyoverse,PROXY
    - GEOSITE,mihoyo-cn,DIRECT
    - GEOSITE,tencent-games,DIRECT
    - GEOSITE,category-games,PROXY
    - GEOSITE,icloud@cn,DIRECT
    - GEOSITE,apple@cn,DIRECT
    - GEOSITE,github,PROXY
    - GEOSITE,gitlab,PROXY
    - GEOSITE,win-spy,REJECT
    - GEOSITE,win-update,REJECT
    - GEOSITE,win-extra,REJECT
    - GEOSITE,gfw,PROXY
    - GEOSITE,greatfire,PROXY
    - GEOSITE,microsoft,PROXY
    - GEOSITE,microsoft-dev,PROXY
    - GEOSITE,microsoft@cn,DIRECT
    - GEOSITE,google@cn,PROXY
    - GEOSITE,google,PROXY

    - GEOSITE,cloudflare@cn,DIRECT
    - GEOSITE,cloudflare,PROXY
    - GEOIP,cloudflare@cn,DIRECT
    - GEOIP,cloudflare,PROXY
    - GEOIP,telegram,PROXY
    - GEOIP,google,PROXY
    - GEOIP,facebook,PROXY
    - GEOIP,twitter,PROXY
    - GEOIP,netflix,PROXY
    - GEOSITE,bilibili,DIRECT,no-resolve
    - GEOSITE,cn,DIRECT
    - GEOIP,CN,DIRECT
    - GEOSITE,geolocation-cn,DIRECT
    - GEOSITE,geolocation-!cn,PROXY
    - GEOIP,LAN,DIRECT,no-resolve

    - MATCH,PROXY
```

### 日志

```raw
06-02 20:26:30.876 16204 16234 I ClashMetaForAndroid: Start initial configuration in progress
06-02 20:26:30.876 16204 16234 D ClashMetaForAndroid: GlobalClientFingerprint:firefox
06-02 20:26:30.893 16204 16234 I ClashMetaForAndroid: Geodata Loader mode: memconservative
06-02 20:26:30.893 16204 16235 I ClashMetaForAndroid: Can't find GeoSite.dat, start download
06-02 20:26:30.895 16204 16234 D ClashMetaForAndroid: [Rule] use default rules
06-02 20:26:35.898 16204 16429 W ClashMetaForAndroid: [TCP] dial DIRECT clash.meta --> testingcf.jsdelivr.net:443 error: connect failed: dial tcp 104.16.85.20:443: i/o timeout | dial tcp 104.16.87.20:443: i/o timeout | dial tcp 104.16.86.20:443: i/o timeout | dial tcp 104.16.89.20:443: i/o timeout | dial tcp 104.16.88.20:443: i/o timeout | connect failed: dial tcp [2606:4700::6810:5514]:443: connect: network is unreachable | dial tcp [2606:4700::6810:5714]:443: connect: network is unreachable | dial tcp [2606:4700::6810:5914]:443: connect: network is unreachable | dial tcp [2606:4700::6810:5614]:443: connect: network is unreachable | dial tcp [2606:4700::6810:5814]:443: connect: network is unreachable
06-02 20:26:35.899 16204 16429 E ClashMetaForAndroid: can't initial GeoSite: can't download GeoSite.dat: Get "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat": EOF
```

### 屏幕截图

![IMG_20230602_201347](https://github.com/MetaCubeX/ClashMetaForAndroid/assets/53572814/4fdf03d7-4aa6-4cc1-854b-4cc62f5f9596)

### 附加信息

是否应当添加允许用户自定义 `geox-url` 或相关文件来源的功能？
