### ISSUE TITLE
[BUG] 无法使用hysteria节点, log报错socket: operation not permitted

### ISSUE THREAD

**Issue by aries1998** [MetaCubeX/ClashMetaForAndroid#103]
### 描述此错误

无法使用hysteria节点，打开cmfa的logcat看，报错如下，都是socket: operation not permitted.
使用其他类型节点比如v2ray都没有问题.
hysteria节点本身确定没问题，使用hysteria原生客户端或者openclash等都能正常连接。 

```
[TCP] dial vps-nodes (match RuleSet/Google) 127.0.0.1:41625 --> history.google.com:443 error: dial ip:tcp  ...... socket: operation not permitted
```

### 如何复现该错误

切换hysteria节点

### 设备信息

- 机型: 红米note5
- 系统类型: PixelExperience
- Android 版本: 11

### 应用信息

- 版本:2.8.5, 2.8.7
- 安装包文件名: cmfa-2.8.7-meta-arm64-v8a-release.apk
- 应用来源: github

### 配置文件

```yml
- name: "vps-de@hysteria"
  type: hysteria
  server: '.......'
  port: 38383
  skip-cert-verify: true
  alpn:
    - h3
  protocol: faketcp
  obfs: 123456
  auth_str: wawawa
  up: "100 Mbps"
  down: "100 Mbps"
```

### 日志

```raw
[TCP] dial vps-nodes (match RuleSet/Google) 127.0.0.1:41625 --> history.google.com:443 error: dial ip:tcp  ...... socket: operation not permitted
```
