### ISSUE TITLE
[BUG] When a config file contains VLESS proxy, all v2ray proxy disappeared in selector

### ISSUE THREAD

**Issue by lotusproxy** [MetaCubeX/ClashMetaForAndroid#106]
### Describe the bug

When a config file contains VLESS proxy, all v2ray proxy(vmess/vless) disappeared in selector, but hysteria still there

### To Reproduce

Import one config with vless

### Device Info

I'm sure this is not caused by system, tried on multiple devices

### Application Info

- Version: 2.8.7 Meta
- Distribution Channel: github release

### Configure File

```yml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
global-client-fingerprint: firefox
ipv6: true
proxy-groups:
    - { name: Switcher, type: select, proxies: ['Auto'] }
    - { name: Auto, type: fallback, proxies: [], url: "http://cp.cloudflare.com/", interval: 7200 }
sniffer:
  enable: true
  override-destination: true
  sniffing:
    - tls
    - http
dns:
    enable: true
    listen: 0.0.0.0:8853
    enhanced-mode: redir-host
    nameserver: ['tls://1.1.1.1', 'tls://1.0.0.1', 'https://1.1.1.1/dns-query', 'https://1.0.0.1/dns-query']
    ipv6: true
rules:
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'IP-CIDR6,fe80::/10,DIRECT'
    - 'MATCH,Switcher'
proxies:
     - { name: demo, type: vless, server: example.com, port: 443, uuid: 0d853a5b-e56f-4b46-bcca-3383b9e5f53d, udp: true, tls: true, servername: example.com, network: grpc, grpc-opts: { grpc-service-name: tunnel } }
```

### Logs

```raw
Not captured
```
