### ISSUE TITLE
[BUG] provider 里的 interval 好像没用，每次启动都会更新一次订阅

### ISSUE THREAD

**Issue by yiwen985** [MetaCubeX/ClashMetaForAndroid#140]
### 描述此错误

`provider` 里的 `interval` 好像没用，每次启动都会更新一次订阅。
点击启动，然后迅速点代理，分组名字后面会显示 COMPATIBLE。
返回主界面，然后点代理，分组后会显示节点。
![Screenshot_2023-09-11-01-57-38-943_com github metacubex clash meta](https://github.com/MetaCubeX/ClashMetaForAndroid/assets/32293747/01b60bbb-3fef-422a-8987-06c91064bcbe)

### 如何复现该错误

...

### 设备信息

- 机型: 小米
- 系统类型: MIUI 14
- Android 版本: 13

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
######### 锚点 start #######
#这里是订阅更新和延迟测试相关的
p: &p {type: http, interval: 86400}

use: &use
  type: select
  use:
  - provider1
  - provider2

######### 锚点 end #######


# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    <<: *p
    url: ""
    path: ./provider1.yaml

  provider2:
    <<: *p
    url: ""
    path: ./provider2.yaml

proxy-groups:
  - {name: 默认, type: select, proxies: [全部节点, 香港, 新加坡, 台湾, 日本, 美国, 其它地区, 自动选择, DIRECT]}
  - {name: 香港, <<: *use,filter: "(?i)港|hk|hongkong|hong kong", type: select}
  - {name: 新加坡, <<: *use, filter: "(?i)(新|sg|singapore)", type: select}
  - {name: 日本, <<: *use, filter: "(?i)日本|jp|japan", type: select}
  - {name: 全部节点, <<: *use, type: select}
  - {name: 台湾, <<: *use, filter: "(?i)台|tw|taiwan", type: select}
  - {name: 美国, <<: *use, filter: "(?i)美|us|unitedstates|united states", type: select}
  - {name: 其它地区, <<: *use, filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*", type: select}
  - {name: 自动选择, <<: *use, tolerance: 100, type: url-test, lazy: true}
```

### 日志

```raw
无
```
