### ISSUE TITLE
[BUG] UDP匹配不到规则

### ISSUE THREAD

**Issue by Mortalit** [MetaCubeX/ClashMetaForAndroid#169]
### 描述此错误

UDP匹配不到规则

### 如何复现该错误

使用relay组

### 设备信息

- 机型:
- 系统类型:
- Android 版本:9

### 应用信息

- 版本:2.8.9

### 配置文件

```yml
proxies:
  - name: 自建节点
    type: socks5
    udp: true
  - name: 机场节点
    type: vmess
    udp: true

proxy-groups:
  - name: Google
    type: select
    proxies:
      - 自建中转
  - name: 自建中转
    type: relay
    proxies:
      - 机场节点
      - 自建节点

rules:
  - DOMAIN-SUFFIX,googleapis.com,Google
  - DOMAIN-SUFFIX,gstatic.com,Google
  - DOMAIN-KEYWORD,gmail,Google
  - DOMAIN-KEYWORD,google,Google
  - MATCH,Google
```

### 日志

```raw
15:56:18.393    Info: [UDP] 172.19.0.1:40445 --> play-fe.googleapis.com:443 doesn't match any rule using DIRECT
15:56:20.007    Info: [TCP] 172.19.0.1:49824 --> connectivitycheck.gstatic.com:443 match DomainSuffix(gstatic.com) using Google[自建节点]
```

### 附加信息

Meta不是支持udp走Relay策略组吗?还是我理解错了
该怎么设置让udp也被代理呢,MATCH也没用
