### ISSUE TITLE
[Feature Request] 求个SS2022的模板

### ISSUE THREAD

**Issue by offferu** [MetaCubeX/ClashMetaForAndroid#29]
### Feature Description

ss2022, 最好ss2022+grpc的也有，非常感谢！

**Comment by qist** [comment]
ss2022+grpc 还不支持
```
**  - name: shadowsocks
    type: ss
    server: ip
    port: 443
    cipher: 2022-blake3-aes-256-gcm
    password:  password
    udp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      host: 域名
      tls: true
      skip-cert-verify: false
      path: "/"
      mux: false
      headers:
        custom: 域名
**
```
