### ISSUE TITLE
[BUG] Latest version 2.5.13-pre01.Meta-Alpha cannot save configuration file

### ISSUE THREAD

**Issue by Kingsmanvn-Official** [MetaCubeX/ClashMetaForAndroid#31]
### Describe the bug

Latest version 2.5.13-pre01.Meta-Alpha cannot save configuration file.
After pressing save it will stay at the verification stage and will not be able to save successfully.
I have tried reinstalling the old version 2.5.12-pre03.Meta-Alpha and confirmed that the config file is completely saved and usable.

### To Reproduce

Step 1: import more configuration files 
Step 2: save configuration

### Device Info

- Device: Redmi Note 11 Pro Plus 5G
- ROM: MIUI Global 13.0.3
- Android Version: 12

### Application Info

- Version:  2.5.13-pre01.Meta-Alpha
- APK filename: cmfa-2.5.13-pre01-meta-alpha-arm64-v8a-release.apk
- Distribution Channel: GitHub

### Configure File

fully configured and working at version 2.5.12-pre03.Meta-Alpha

```yaml
#port: 7890
#socks-port: 7891
authentication:
  - "kingsmanvn:kingsmanvn"
tcp-concurrent: true
allow-lan: true
bind-address: '*'
mode: rule
ipv6: true
log-level: debug
external-controller: 127.0.0.1:9090
secret: "kingsmanvn"
clash-for-android:
  append-system-dns: true
profile:
  store-selected: false
  store-fake-ip: true
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: false
dns:
  enable: true
  #listen: 127.0.0.1:1053
  prefer-h3: true
  ipv6: true
  use-hosts: true
  default-nameserver:
    - 8.8.8.8
    - 9.9.9.11
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
  nameserver:
    #- 'localhost:11053#h3=true'
    #- quic://id.dns.nextdns.io:8853
    - 'https://doh3.dns.nextdns.io/id/kingsmanvn%20clash%20meta#h3=true'
    #- tls://kingsmanvn--clash--meta-id.dns.nextdns.io:8853
    #- dhcp://system
  proxy-server-nameserver:
    #- 'localhost:11053#h3=true'
    #- quic://kingsmanvn--clash--meta-id.dns.nextdns.io:8853
    - 'https://doh3.dns.nextdns.io/id/kingsmanvn%20clash%20meta#h3=true'
    #- tls://kingsmanvn--clash--meta-id.dns.nextdns.io:8853
    #- dhcp://system
  fallback:
    #- 'localhost:11053#h3=true'
    #- quic://id.dns.nextdns.io:8853
    - 'https://doh3.dns.nextdns.io/id/kingsmanvn%20clash%20meta#h3=true'
    #- tls://kingsmanvn--clash--meta-id.dns.nextdns.io:8853
    #- dhcp://system
  fallback-filter:
    geoip: true
    ipcidr: 
      - 240.0.0.0/4
      - 0.0.0.0/32
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
proxies:
  - name: '🇭🇰 Surfshark HK HKG WireGuard'
    type: wireguard
    udp: true
    dns: [162.252.172.57, 149.154.159.92]
  - name: '🇸🇬 Surfshark SG SNG WireGuard'
    type: wireguard
    udp: true
    dns: [162.252.172.57, 149.154.159.92]
  #- name: ADGUARD
    #type: http
    #server: 127.0.0.1
    #port: 9000
  #- name: '🇸🇬 SG snell'
    #type: snell
d: &d
  type: http
  url: "http://yunavpn.com/api/v1/client/subscribe?token=xxx"
  interval: 3600
  path: ./proxyset/yuna.yaml
  health-check:
    enable: true
    interval: 600
    url: http://dns.nextdns.io/generate_204
proxy-providers:
  yuna:
    <<: *d
    filter: '^(?=.*)((?!(TADMIN|TIKTOK)).)*$'
    #filter: ^(.*)(GADMIN|GARENA)+(.*)$
proxy-groups:
  - name: KINGSMANVN
    type: select
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    proxies:
      - '♻️TỰ ĐỘNG CHỌN SERVER PING NGON NHẤT'
      - '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER ỔN ĐỊNH NHẤT'
      - '♻️TỰ ĐỘNG CHỌN SERVER VN PING NGON NHẤT'
      - '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER VN ỔN ĐỊNH NHẤT'
      - '♻️TỰ ĐỘNG CHỌN SERVER SG PING NGON NHẤT'
      - '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER SG ỔN ĐỊNH NHẤT'
      - '♻️TỰ ĐỘNG CHỌN SERVER SURFSHARK PING NGON NHẤT'
      - '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER SURFSHARK ỔN ĐỊNH NHẤT'
      - '🇭🇰 Surfshark HK HKG WireGuard'
      - '🇸🇬 Surfshark SG SNG WireGuard'
      #- '🇸🇬 SG snell'
  #- name: HACK5G
    #type: relay
    #proxies:
      #- KINGSMANVN
      #- ADGUARD
  - name: '♻️TỰ ĐỘNG CHỌN SERVER SURFSHARK PING NGON NHẤT'
    type: url-test
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    proxies:
      - '🇭🇰 Surfshark HK HKG WireGuard'
      - '🇸🇬 Surfshark SG SNG WireGuard'
    filter: '^(?=.*(Surfshark).)*$'
  - name: '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER SURFSHARK ỔN ĐỊNH NHẤT'
    type: fallback
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    proxies:
      - '🇭🇰 Surfshark HK HKG WireGuard'
      - '🇸🇬 Surfshark SG SNG WireGuard'
    filter: '^(?=.*(Surfshark))+(.*)$'
  - name: '♻️TỰ ĐỘNG CHỌN SERVER PING NGON NHẤT'
    type: url-test
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    proxies:
      #- '🇸🇬 SG snell'
  - name: '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER ỔN ĐỊNH NHẤT'
    type: fallback
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    proxies:
      #- '🇸🇬 SG snell'
  - name: '♻️TỰ ĐỘNG CHỌN SERVER VN PING NGON NHẤT'
    type: url-test
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http:/dns.nextdns.io/generate_204
    use:
      - yuna
    filter: '^(?=.*(🇻🇳|VN|HN|HCM)).*((?!(Surfshark)).)*$'
  - name: '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER VN ỔN ĐỊNH NHẤT'
    type: fallback
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    filter: '^(?=.*(🇻🇳|VN|HN|HCM)).*((?!(Surfshark)).)*$'
  - name: '♻️TỰ ĐỘNG CHỌN SERVER SG PING NGON NHẤT'
    type: url-test
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    filter: '^(?=.*(🇸🇬|新|狮|獅|SG|Singapore|SINGAPORE)).*((?!(Surfshark)).)*$'
  - name: '🔯TỰ ĐỘNG CHUYỂN ĐỔI SERVER SG ỔN ĐỊNH NHẤT'
    type: fallback
    url: http://dns.nextdns.io/generate_204
    interval: 420
    health-check:
      enable: true
      interval: 420
      url: http://dns.nextdns.io/generate_204
    use:
      - yuna
    filter: '^(?=.*(🇸🇬|新|狮|獅|SG|Singapore|SINGAPORE)).*((?!(Surfshark)).)*$'
rule-providers:
  hostsvn:
    behavior: "domain"
    type: http
    url: "https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-clash-rule.yaml"
    interval: 72240
    path: ./ruleset/hostsvn.yaml
  rejectfile:
    type: http
    behavior: "domain"
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/rejectfile.yaml
    interval: 86400
rules:
  - RULE-SET,hostsvn,REJECT
  - RULE-SET,rejectfile,REJECT
  - DOMAIN,www.googleadservices.com,REJECT
  - DOMAIN,googleads.g.doubleclick.net,REJECT
  - IP-CIDR,0.0.0.0/32,REJECT,no-resolve
  #- IP-CDIR6,::/128,REJECT,no-resolve
  - MATCH,KINGSMANVN
  
```

### Logs

```raw
no logs
```

### Screenshot

![Screenshot_2022-12-09-13-49-13-280_com github metacubex clash meta](https://user-images.githubusercontent.com/94727017/206645966-79012da7-2081-4eab-905a-129dddafa139.jpg)
