### ISSUE TITLE
[BUG] 流量经过app后，延迟升高

### ISSUE THREAD

**Issue by never-afk** [MetaCubeX/ClashMetaForAndroid#34]
### Describe the bug

我主要使用ad过滤功能，但是日常玩pubg mobile，发现延迟会升高
![Screenshot_20221212_123934_com tencent ig](https://user-images.githubusercontent.com/17429958/206962620-a8f98067-84fb-4a03-9bce-b04c057edb71.jpg)
<img width="773" alt="WX20221212-124446@2x" src="https://user-images.githubusercontent.com/17429958/206962648-b013781b-7ca2-48db-92a8-54dd945e09df.png">

为了排除是规则的问题，故将meta 设置 -- 覆写--- 模式 -- 直连 进行尝试

发现延迟无任何改善，必须关闭meta clash 才行

### To Reproduce

Step 1: ...
打开meta android 使用直连模式
Step 2: ...
打开pubg mobile
Step 3: ...
...
游戏内延迟显著升高。
ps：如果不开cmfa，延迟大约在60ms

### Device Info

- Device: 华为P40 PRO
- ROM: 战狼OS 2.0.0.280
- Android Version: 看不见

### Application Info

- Version:2.5.13-pre04.Meta-Alpha
- APK filename:2.5.13-pre04.Meta-Alpha V8
- Distribution Channel:github 

### Configure File

```yml
socks-port: 7891
mode: rule
log-level: info
enable-process: false
sniffer:
    enable: true
    sniffing:
        - http
        - tls
dns:
    enable: true
    nameserver:
        - 8.8.8.8
        - 1.1.1.1
    fallback:
        - 223.5.5.5
        - 223.6.6.6
        - 114.114.114.114
    listen: 0.0.0.0:55553
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
tun:
    enable: true
    stack: System
    dns-hijack:
        - 0.0.0.0:53
    auto-route: true
    auto-detect-interface: true
proxies:
proxy-groups:
    - name: Direct
      proxies:
        - DIRECT
      type: select
    - name: Reject
      proxies:
        - REJECT
      type: select
rules:
    - MATCH,Direct
```

### Logs

```raw
i will try
```
