### ISSUE TITLE
[BUG] 由VPN路由流量时无法查询dns

### ISSUE THREAD

**Issue by hooUmAi** [MetaCubeX/ClashMetaForAndroid#51]
### 描述此错误

开启“自动路由系统流量”时无法通过default-nameserver解析nameserver中的域名
不开启VPN通过curl -x socks5://localhost:mix-port时无此现象

### 如何复现该错误

步骤 1: 导入配置启用VPN路由termux流量
步骤 2: 在termux中执行curl https://github.com

### 设备信息

- 机型:
- 系统类型:
- Android 版本: 13

### 应用信息

- 版本: 2.6.8.Meta-Alpha
- 安装包文件名: cfma-2.6.8-meta-alpha-armeabi-v7a-release-1.apk
- 应用来源: Github Release

### 配置文件

```yml
mixed-port: 7891
allow-lan: false
bind-address: "*"
mode: rule
log-level: debug

ipv6: true

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - "119.29.29.29"
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost
    - '*.my.server'
  nameserver:
    - tls://dot.my.server:853

proxies:
  - name: "vless"
    type: vless
    server: "proxy.my.server"
    port: 8443
    uuid: whatever-some-uuid
    network: tcp
    udp: true
    tls: true
    xudp: true
    flow: xtls-rprx-vision
    client-fingerprint: firefox

rules:
  - DOMAIN-SUFFIX,my.server,DIRECT
  - IP-CIDR,119.29.29.29/32,DIRECT,no-resolve
  - IP-CIDR,223.5.5.5/32,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - DOMAIN,localhost,DIRECT

  - MATCH,vless
```

### 日志

```raw
# Capture on xxxx-xx-xx xx:x1:40.048
xx:x1:40.050    Info: [APP] Logcat level: info
xx:x1:40.051    Info: [APP] request force GC
xx:x1:49.155    Info: Start initial configuration in progress
xx:x1:49.158    Info: Geodata Loader mode: memconservative
xx:x1:49.164 Warning: Deprecated: Use Sniff instead
xx:x1:49.165    Info: Initial configuration complete, total time: 8ms
xx:x1:49.165    Info: Sniffer is closed
xx:x1:49.165    Info: Start initial compatible provider default
xx:x1:49.186    Info: dns:
xx:x1:49.189    Info:   enable: true
xx:x1:49.189    Info:   prefer-h3: false
xx:x1:49.190    Info:   ipv6: true
xx:x1:49.191    Info:   use-hosts: true
xx:x1:49.193    Info:   nameserver:
xx:x1:49.194    Info:   - tls://dot.my.server:853
xx:x1:49.194    Info:   fallback: []
xx:x1:49.194    Info:   fallback-filter:
xx:x1:49.195    Info:     geoip: true
xx:x1:49.195    Info:     geoip-code: CN
xx:x1:49.195    Info:     ipcidr: []
xx:x1:49.195    Info:     domain: []
xx:x1:49.195    Info:     geosite: []
xx:x1:49.195    Info:   listen: ""
xx:x1:49.196    Info:   enhanced-mode: fake-ip
xx:x1:49.196    Info:   fake-ip-range: 198.18.0.1/16
xx:x1:49.199    Info:   fake-ip-filter:
xx:x1:49.200    Info:   - '*.lan'
xx:x1:49.200    Info:   - localhost
xx:x1:49.200    Info:   - '*.my.server'
xx:x1:49.200    Info:   default-nameserver:
xx:x1:49.200    Info:   - 119.29.29.29
xx:x1:49.200    Info:   nameserver-policy: {}
xx:x1:49.200    Info:   proxy-server-nameserver: []
xx:x1:49.201    Info: 
xx:x1:49.201    Info: Start initial configuration in progress
xx:x1:49.201    Info: Geodata Loader mode: memconservative
xx:x1:49.201 Warning: Deprecated: Use Sniff instead
xx:x1:49.201    Info: Initial configuration complete, total time: 8ms
xx:x1:49.201    Info: Sniffer is closed
xx:x1:49.201    Info: Start initial compatible provider default
xx:x1:49.201    Info: Mixed(http+socks) proxy listening at: 127.0.0.1:7891
xx:x1:49.207   Debug: TUN: fd = 97, gateway = 172.19.0.1/30, portal = 172.19.0.2, dns = 0.0.0.0
xx:x1:54.577   Debug: [Rule] use default rules
xx:x1:54.578   Debug: [DNS] resolve proxy.my.server from tls://dot.my.server:853
xx:x1:54.579   Debug: [DNS] resolve dot.my.server from udp://119.29.29.29:53
xx:x1:54.580   Debug: [DNS] resolve proxy.my.server from tls://dot.my.server:853
xx:x1:54.582   Debug: [DNS] resolve dot.my.server from udp://119.29.29.29:53
xx:x1:54.583   Debug: [DNS] resolve dot.my.server from tls://dot.my.server:853
xx:x1:54.583   Debug: [DNS] resolve dot.my.server from tls://dot.my.server:853
xx:x1:59.579 Warning: [TCP] dial vless (match Match/) 172.19.0.1:41562 --> github.com:443 error: proxy.my.server:8443 connect error: dns resolve failed: couldn't find ip
xx:x1:59.580   Debug: [DNS] resolve proxy.my.server from tls://dot.my.server:853
xx:x1:59.580   Debug: [DNS] resolve dot.my.server from udp://119.29.29.29:53
xx:x1:59.580   Debug: [DNS Server] Exchange ;dot.my.server.	IN	 AAAA failed: all DNS requests failed, first error: use default dns resolve failed: couldn't find ip
xx:x1:59.581   Debug: [DNS] resolve dot.my.server from tls://dot.my.server:853
xx:x1:59.581   Debug: [DNS Server] Exchange ;dot.my.server.	IN	 A failed: all DNS requests failed, first error: use default dns resolve failed: couldn't find ip
xx:x1:59.581   Debug: [DNS] resolve dot.my.server from tls://dot.my.server:853
xx:x1:59.582   Debug: [DNS] resolve dot.my.server from udp://119.29.29.29:53
xx:x2:04.580   Debug: [DNS Server] Exchange ;dot.my.server.	IN	 A failed: all DNS requests failed, first error: use default dns resolve failed: couldn't find ip
xx:x2:04.582   Debug: [DNS Server] Exchange ;dot.my.server.	IN	 AAAA failed: all DNS requests failed, first error: use default dns resolve failed: couldn't find ip
```
