### ISSUE TITLE
[BUG] url-test 类型是否可用？

### ISSUE THREAD

**Issue by perthun** [MetaCubeX/ClashMetaForAndroid#63]
### 描述此错误

平时使用时，发现策略组选择的代理极少改变，哪怕网络延迟800+也是如此。

使用 proxy-providers 订阅的节点，App 已加入电池优化白名单，不存在网络问题，经过测试发现：

每次开启代理后，转发都默认使用 urltest 类型策略组中的第一个代理，较长时间后也不会自动更换——哪怕网络条件很差、访问速度很慢也是如此

手动点了测速、才会更换

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: 红米 K40
- 系统类型: LineageOS
- Android 版本: 12

### 应用信息

- 版本: 2.7.0.Meta-Alpha
- 安装包文件名: com.github.metacubex.clash.meta
- 应用来源: f-droid

### 配置文件

```yml
proxy-groups:
  - name: 手动选择
    type: select
    proxies:
      - 优选最快
      - DIRECT
    use:
      - EEVPN
      - ilol
  - name: 优选最快
    type: url-test
    use:
      - EEVPN
      - ilol
    filter: '^(?!.*(?:香港|土耳其|柬埔寨|越南|缅甸)).*$'      # 使用正则表达式排除节点
    url: http://www.gstatic.com/generate_204
    interval: 300

# 所有流量都先导入到 手动选择，然后再导入 优选最快
# 但 优选最快 策略组，几乎不变改变选择的代理，无论网络情况，只有极少数情况才会变化
```

### 日志

```raw
通过通过检查Debug级别的日志，持续300秒以上的时间（我看了2次，一次5分钟、一次10分钟），没有新的日志出现，没有执行健康检查，手动点了测速，才有 `Health Checking` 的日志出现

如果这样的话，interval 的设置就没有意义了，根本不会间隔XX秒然后测速。应用是否出现了 BUG
```

### 附加信息

另外我想咨询一下，geosite和geoip文件的更新间隔是多少？能在配置文件中设置吗？

**Comment by Se7entny** [comment]
轻为你的proxy-providers:设置health-check:配置
如
```
proxy-providers:
  ONE:
    type: http
    url: ""
    path: ./ONE.yaml
    interval: 72000
    health-check:
      enable: true
      interval: 1800
      url: http://www.gstatic.com/generate_204

```
