### ISSUE TITLE
[BUG] The routing rule file configured in geox-url cannot be automatically downloaded

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/ClashMetaForAndroid#69]
### Describe the bug

For example, I generated the geosite.dat routing rule file myself, added the category "geosite:network", and configured "geox-url" to point "geosite" to the direct link of the geosite.dat file generated by myself. After importing the configuration, an error will be reported. 
Or is there any way to import my own geosite.dat file?

### To Reproduce

Step 1: ...
Step 2: ...
Step 3: ...
...

### Device Info

- Device:
- ROM:
- Android Version:

### Application Info

- Version:
- APK filename:
- Distribution Channel:

### Configure File

```yml
geox-url:
  geosite: "https://fastly.jsdelivr.net/gh/DustinWin/clash-geosite@release/geosite.dat"
  geoip: "https://fastly.jsdelivr.net/gh/DustinWin/clash-geoip@release/geoip.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/DustinWin/clash-geoip@release/Country.mmdb"
```
```


### Logs

```raw
......
```
