### ISSUE TITLE
[BUG] yaml:line 20: did not find expected key.

### ISSUE THREAD

**Issue by isaac574** [MetaCubeX/ClashMetaForAndroid#74]
### 描述此错误

无法运行VLESS WS协议；

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: REALME GT NEO
- 系统类型:
- Android 版本: 13

### 应用信息

- 版本:
- 安装包文件名: cmfa-2.7.4-meta-alpha-armeabi-v7a-release.apk
- 应用来源: GITHUB

### 配置文件

```yml
mixed-port: 7892
allow-lan: true                                                     
mode: rule                                                          
log-level: info                                                     
ipv6: true                                                          
dns:                                                                
  enable: true                                                      
  listen: 0.0.0.0:53                                                
  ipv6: true                                                        
  default-nameserver:                                               
    - 114.114.114.114                                               
    - 223.5.5.5                                                     
  enhanced-mode: redir-host                                         
  nameserver:                                                       
    - https://dns.alidns.com/dns-query                              
    - https://223.5.5.5/dns-query                                   
  fallback:                                                         
    - 114.114.114.114                                               
    - 223.5.5.5                                                     
proxies: 
  - name: "vless-ws-hosteons"
    type: vless
    server: XXX.XXXXXXXXX.XX
    port: 443
    uuid: e3b24d4b-XXXX-4e1f-8fd1-36a2a4f88abe
    udp: true
    tls: true
    network: ws
    # client-fingerprint: random # Available: "chrome","firefox","safari","random","none"
    servername: XXX.XXXXXXXXX.XX # priority over wss host
    skip-cert-verify: true
    # fingerprint: xxxx
    ws-opts:
      path: "/XXXXXX"
      headers:
      Host: xxx.xxxxxx.xx  
proxy-groups:                                                       
  - name: "PROXY"                                                   
    type: select                                                    
    proxies:                                                        
     - vless-ws-hosteons                                               
rule-providers:                                                     
  reject:                                                           
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"                            
    path: ./ruleset/reject.yaml                                     
    interval: 86400                                                 
  icloud:                                                           
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"                            
    path: ./ruleset/icloud.yaml                                     
    interval: 86400                                                 
  apple:                                                            
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"                             
    path: ./ruleset/apple.yaml                                      
    interval: 86400                                                 
  google:                                                           
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"                            
    path: ./ruleset/google.yaml                                     
    interval: 86400                                                 
  proxy:                                                            
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"                             
    path: ./ruleset/proxy.yaml                                      
    interval: 86400                                                 
  direct:                                                           
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"                            
    path: ./ruleset/direct.yaml                                     
    interval: 86400                                                 
  private:                                                          
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"                           
    path: ./ruleset/private.yaml                                    
    interval: 86400                                                 
  gfw:                                                              
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"                               
    path: ./ruleset/gfw.yaml                                        
    interval: 86400                                                 
  greatfire:                                                        
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"                         
    path: ./ruleset/greatfire.yaml                                  
    interval: 86400                                                 
  tld-not-cn:                                                       
    type: http                                                      
    behavior: domain                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"                        
    path: ./ruleset/tld-not-cn.yaml                                 
    interval: 86400                                                 
  telegramcidr:                                                     
    type: http                                                      
    behavior: ipcidr                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"                      
    path: ./ruleset/telegramcidr.yaml                               
    interval: 86400                                                 
  cncidr:                                                           
    type: http                                                      
    behavior: ipcidr                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"                            
    path: ./ruleset/cncidr.yaml                                     
    interval: 86400                                                 
  lancidr:                                                          
    type: http                                                      
    behavior: ipcidr                                                
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"                           
    path: ./ruleset/lancidr.yaml                                    
    interval: 86400                                                 
  applications:                                                     
    type: http                                                      
    behavior: classical                                             
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"                      
    path: ./ruleset/applications.yaml                               
    interval: 86400                                                 
rules:                                                              
  - RULE-SET,applications,DIRECT                                    
  - DOMAIN,clash.razord.top,DIRECT                                  
  - DOMAIN,yacd.haishan.me,DIRECT                                   
  - RULE-SET,private,DIRECT                                         
  - RULE-SET,reject,REJECT                                          
  - RULE-SET,icloud,DIRECT                                          
  - RULE-SET,apple,DIRECT                                           
  - RULE-SET,google,DIRECT                                          
  - RULE-SET,proxy,PROXY                                            
  - RULE-SET,direct,DIRECT                                          
  - RULE-SET,lancidr,DIRECT                                         
  - RULE-SET,cncidr,DIRECT                                          
  - RULE-SET,telegramcidr,PROXY                                     
  - GEOIP,LAN,DIRECT                                                
  - GEOIP,CN,DIRECT                                                 
  - MATCH,PROXY
```

### 日志

```raw
yaml:line 20: did not find expected key.
```
