### ISSUE TITLE
[BUG] tuic ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by moeshin** [MetaCubeX/ClashMetaForAndroid#76]
### 描述此错误

单独运行内核 `alpha-b8179eb` 同配置正常
2.7.2.Meta-Alpha 正常

### 如何复现该错误

步骤 1: 打开 Chrome
步骤 2: 访问 Google

### 设备信息

- 机型: Redmi K60 Pro
- 系统类型: MIUI
- Android 版本: 13

### 应用信息

- 版本: 2.7.4.Meta-Alpha
- 安装包文件名:
- 应用来源: F-Droid

### 配置文件

```yml
port: 7890
socks-port: 7891
#redir-port: 7892
#tproxy-port: 7893
mixed-port: 6666

mode: Rule
log-level: info
ipv6: false
udp: true
tcp-concurrent: true

external-controller: 127.0.0.1:9090
#external-ui: yacd

allow-lan: false
bind-address: '*'

# >>> Android
# https://github.com/MetaCubeX/Clash.Meta/issues/91
enable-process: true

clash-for-android:
  append-system-dns: false
# <<< Android


experimental:
  sniff-tls-sni: true

profile:
  store-selected: true
  tracing: true
  store-fake-ip: true

tun:
  enable: false
  stack: gvisor
  dns-hijack:
    - 0.0.0.0:53
    - any:53
  auto-detect-interface: true
  auto-route: true
  mtu: 9000
  strict_route: true
  inet4_route_address:
    - 0.0.0.0/1
    - 128.0.0.0/1
  inet6_route_address:
    - ::/1
    - 8000::/1
  endpoint_independent_nat: false

sniffer:
  enable: true
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.apple.com
    - '*.baidu.com'
  force-domain:
    - google.com
  sniffing:
    - tls
    - http
  port-whitelist: [80, 443]

geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb

dns:
  enable: true
  listen: :1053
  use-hosts: true
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  nameserver:
    - tls://1.12.12.12:853
    - tls://120.53.53.53:853
    - tls://223.5.5.5:853
    - tls://1.1.1.1
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  nameserver-policy:
    geosite:cn: https://1.12.12.12/dns-query
  enhanced-mode: fake-ip
#  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    - stun.*.*.*
    - stun.*.*
    - miwifi.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - netis.cc
    - router.asus.com
    - repeater.asus.com
    - routerlogin.com
    - routerlogin.net
    - tendawifi.com
    - tendawifi.net
    - tplinklogin.net
    - tplinkwifi.net
    - tplinkrepeater.net
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - localhost.ptlogin2.qq.com
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - xbox.*.*.microsoft.com
    - '*.ipv6.microsoft.com'
    - '*.*.xboxlive.com'
    - speedtest.cros.wr.pvp.net
    - +.cn
    - +.10010.com
    - +.chinaunicom.com
    - +.baidu.com
    - '*.alipay.com'
    - '*.alipayobjects.com'
    - '*.jijifun.com'
    - connect.rom.miui.com
    - +.msftnsci.com
    - dl.google.com
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '*.*.*.*.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '*.*.*.stun.playstation.net'
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - '*.*.*.xboxlive.com'
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
proxies: []
proxy-groups:
  - name: MODE
    type: select
    proxies:
      - PROXY
      - RELAY
  - name: PROXY
    type: select
    proxies:
      - URL TEST
      - DIRECT
      - LAN
#      - load-balance
  - name: URL TEST
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies: []
#  - name: load-balance
#    type: load-balance
#    strategy: consistent-hashing
#    url: http://www.gstatic.com/generate_204
#    interval: 300
#    proxies: []
  - name: LAN
    type: select
    proxies:
      - DIRECT
  - name: APPLE
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: RELAY
    type: relay
    proxies:
      - PROXY
      - relay-dest
rules:
  - PROCESS-NAME,clash-meta,DIRECT
  - PROCESS-NAME,clash-meta.exe,DIRECT
  - PROCESS-NAME,clashMeta,DIRECT
  - PROCESS-NAME,clashMeta.exe,DIRECT
  - PROCESS-NAME,clash,DIRECT
  - PROCESS-NAME,clash.exe,DIRECT
  - PROCESS-NAME,frpc,DIRECT
  - PROCESS-NAME,frpc.exe,DIRECT
  - PROCESS-NAME,frps,DIRECT
  - PROCESS-NAME,frps.exe,DIRECT
  # https://www.rocschool.com/tool/ipcidr/
  # https://tool.chinaz.com/tools/subnetmask
  - IP-CIDR,192.168.0.1/32,DIRECT
  - IP-CIDR,192.168.1.1/32,DIRECT
  - IP-CIDR,192.168.2.1/32,DIRECT
  - IP-CIDR,10.0.0.1/32,DIRECT
  - IP-CIDR,10.10.0.1/32,DIRECT
  # https://zh.wikipedia.org/wiki/%E4%BF%9D%E7%95%99IP%E5%9C%B0%E5%9D%80
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT

  - DOMAIN,www.bing.com,PROXY
  - DOMAIN,cn.bing.com,DIRECT
  - DOMAIN,apps.apple.com,APPLE

#  - DOMAIN,github.com,PROXY
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

### 日志

```raw
# Capture on 2023-05-05 14:46:00.651
14:46:00.652    Info: [APP] Logcat level: debug
14:46:02.898   Debug: [Rule] use default rules
14:46:02.902   Debug: [PKG] 127.0.0.1:38374 --> www.google.com:443 by 10245[com.android.chrome]
14:46:02.902   Debug: [DNS] www.google.com --> 75.126.135.131
14:46:02.903    Info: [TCP] 127.0.0.1:38374(com.android.chrome) --> www.google.com:443 match Match using PROXY[gcjp]
14:46:03.180   Debug: [Rule] use default rules
14:46:03.184   Debug: [PKG] 127.0.0.1:38390 --> www.google.com:443 by 10245[com.android.chrome]
14:46:03.186   Debug: [DNS] www.google.com --> 75.126.135.131
14:46:03.186    Info: [TCP] 127.0.0.1:38390(com.android.chrome) --> www.google.com:443 match Match using PROXY[gcjp]
14:46:06.356   Debug: [Rule] use default rules
14:46:06.358   Debug: [PKG] 172.19.0.1:44056 --> mtalk.google.com:5228 by 10114[com.google.uid.shared]
14:46:06.358   Debug: [Process] mtalk.google.com from process com.google.uid.shared
14:46:06.359   Debug: [DNS] mtalk.google.com --> 108.177.97.188
14:46:06.359    Info: [TCP] 172.19.0.1:44056(com.google.uid.shared) --> mtalk.google.com:5228 match Match using PROXY[gcjp]
```

### 附加信息

termux curl

```text
> curl -v https://www.google.com
*   Trying 198.18.0.17:443...
* Connected to www.google.com (198.18.0.17) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /data/data/com.termux/files/usr/etc/tls/cert.pem
*  CApath: /data/data/com.termux/files/usr/etc/tls/certs
* OpenSSL/3.1.0: error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) OpenSSL/3.1.0: error:0A00010B:SSL routines::wrong version number
```

```text
# Capture on 2023-05-05 14:48:48.178
14:48:48.180    Info: [APP] Logcat level: debug
14:48:48.181    Info: [APP] request force GC
14:48:54.400   Debug: [Rule] use default rules
14:48:54.404   Debug: [PKG] 127.0.0.1:38778 --> www.google.com:443 by 10237[com.termux]
14:48:54.406   Debug: [DNS] www.google.com --> 199.96.63.163
14:48:54.406    Info: [TCP] 127.0.0.1:38778(com.termux) --> www.google.com:443 match Match using PROXY[gcjp]
14:48:57.180   Debug: [Sniffer] All sniffing sniff failed with from [127.0.0.1:42578] to [183.2.144.17:80]
```
