### ISSUE TITLE
[BUG] 请问hysteria的证书要怎么访问..

### ISSUE THREAD

**Issue by cyfex** [MetaCubeX/ClashMetaForAndroid#98]
### 描述此错误

从Configuration.yaml设置Profile的时候，hysteria的配置里面要指定证书的路径，然而无论指定什么路径，Clash Meta for Android都没有权限访问，比如/storage/emulated/0/hysteria/my.ca.crt 请问证书需要放在哪里这app才有权限访问呢？

### 如何复现该错误

步骤 1: Profile
步骤 2: Create Profile
步骤 3: Import from File
步骤 4: 选择你为hysteria写的Configuration.yaml，其中钦定了  ca: /storage/emulated/0/hysteria/my.ca.crt
步骤 5: 保存该Profile，报错，没有访问该文件的permission

### 设备信息

- 机型: Redmi Note 11 Pro
- 系统类型: MIUI
- Android 版本: 13

### 应用信息

- 版本: 2.8.6
- 安装包文件名: cmfa-2.8.6-meta-arm64-v8a-release.apk 
- 应用来源: GitHub

### 配置文件

```yml
port: 8080
socks-port: 1080

proxies:
  - name: "hysteria"
    type: hysteria
    server: 你猜猜
    port: 你猜猜
    ports: 你猜猜
    # alpn:
    #	- h3
    obfs: 你猜猜
    auth_str: 你猜猜
    up: 20
    down: 28
    sni: www.你猜猜.com
    ca: /storage/emulated/0/hysteria/my.ca.crt

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - hysteria
```

### 日志

```raw
Error
proxy 0: hysteria 你猜猜:你猜猜
load ca error: open /storage/emulated/0/hysteria/my.ca.crt: permission denied
```
