### ISSUE TITLE
[BUG] 无法正确识别shadowsocks-2022 密码长度

### ISSUE THREAD

**Issue by amfiyong** [MetaCubeX/ClashMetaForAndroid#99]
### 描述此错误

32位长度的密码，因该是通用
2022-blake3-aes-128-gcm
2022-blake3-aes-256-gcm
2022-blake3-chacha20-poly1305
当协议是2022-blake3-aes-128-gcm 的时候，app提示必须是16位长度而密码
当协议是2022-blake3-aes-256-gcm 的时候, app提示获取的密码长度是16位
2022-blake3-chacha20-poly1305 协议未测试

可以确定我使用的密码长度是32位。

### 如何复现该错误

步骤 1: ...创建一个shadowsocks-2022 配置文件
步骤 2: ... 打开手机APP
步骤 3: ...导入进去，在导入的时候就会提示错误
...

### 设备信息

- 机型:pixle6
- 系统类型:android
- Android 版本:A13

### 应用信息

- 版本:2.8.6
- 安装包文件名:cmfa-2.8.6-meta-arm64-v8a-release.apk
- 应用来源:github

### 配置文件

```yml
name: TEST
type: ss
server: '127.0.0.1'
port: '50200'
cipher: 2022-blake3-aes-128-gcm
password: 'pyq69BoXoFRWRL42JCkACg==:pWlzk3r//xQ6/99dDW2pxT9PIOwBSEFMUgaPFsEJYN0='
udp: true
```

### 日志

```raw
没有日志
```
